### ISSUE TITLE
Error when running SecBee and unexpected behavior.

### ISSUE THREAD

**Issue by iotfu** [Cognosec/SecBee#5]
Hello,

I've been experiencing difficulties when trying to operate SecBee after installing it.

I've downloaded SecBee as Instructed by the file (While solving some problems it didn't mention) and got everything up and running.
There are several ways in which the program doesn't operate correctly:
1. When I run SecBee the program starts up but the terminal states "ERROR: no module named scanner_802_15_4"
2. When I use the scan feature, wireshark starts with an error but shows nothing even though the terminal writes "New device found".
3. When I load the list of devices they are flawed and hold very little actual information if any information at all. 

I'm running Ubuntu 16.04 on VMWare and using USRP-B200 as my interface.
p.s - I attached screen shots of the whole process in order to make it easier.

![1](https://cloud.githubusercontent.com/assets/22129077/18417089/5d6ebe9a-782f-11e6-9794-df4d62d84b10.png)
![2](https://cloud.githubusercontent.com/assets/22129077/18417091/5d6fea4a-782f-11e6-8cff-8e69292ea230.png)
![3](https://cloud.githubusercontent.com/assets/22129077/18417093/5d717086-782f-11e6-8d98-e42da9ac7396.png)
![4](https://cloud.githubusercontent.com/assets/22129077/18417090/5d6f59a4-782f-11e6-9135-a40bfd614e62.png)
![5](https://cloud.githubusercontent.com/assets/22129077/18417092/5d703324-782f-11e6-9dac-76b284797785.png)

Thanks in advance.

**Comment by zu1na** [comment]
Hi,

do you also have the wireshark connector installed?  https://github.com/bastibl/gr-foo.git https://github.com/bastibl/gr-foo.git

You might have some dependecy issues? I know the install guide has some flaws and I will try to update the guide soon. Any help appreciated! 

Could you provide a screenshot of the ZigBee GRC? 

Best,
Tobias

**Comment by iotfu** [comment]
Thank you for replying so fast!

I have installed the wireshark connector.
here is the screenshot of Zigbee.grc: 
![zigbee grc](https://cloud.githubusercontent.com/assets/22129077/18429059/68708074-789f-11e6-8553-2ca660a786e2.png)
I've tried running it and in the first run it returned with an error. At second run it just halted. (see console log below)

<<< Welcome to GNU Radio Companion v3.7.10.1-46-gf14e6313 >>>

Block paths:
    /home/labpc/.grc_gnuradio
    /usr/local/share/gnuradio/grc/blocks
    /usr/local/share/gnuradio/grc/blocks

Loading: "/home/labpc/secbeedir/SecBee/Zigbee.grc"

> > > Done

Generating: '/home/labpc/secbeedir/SecBee/top_block.py'

Executing: /usr/bin/python2 -u /home/labpc/secbeedir/SecBee/top_block.py

linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.011.000.git-47-g3e352429

(top_block.py:24378): IBUS-WARNING *_: The owner of /home/labpc/.config/ibus/bus is not root!
-- Detected Device: B200
-- Operating over USB 3.
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Setting master clock rate selection to 'automatic'.
-- Asking for clock rate 16.000000 MHz... Traceback (most recent call last):
  File "/home/labpc/secbeedir/SecBee/top_block.py", line 244, in <module>
    main()
  File "/home/labpc/secbeedir/SecBee/top_block.py", line 238, in main
    tb = top_block_cls()
  File "/home/labpc/secbeedir/SecBee/top_block.py", line 125, in **init**
    channels=range(1),
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/uhd/**init**.py", line 122, in constructor_interceptor
    return old_constructor(_args)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/uhd/uhd_swig.py", line 1981, in make
    return _uhd_swig.usrp_source_make(*args)
RuntimeError: EnvironmentError: IOError: Radio ctrl (0) packet parse error - AssertionError: packet_info.packet_count == (seq_to_ack & 0xfff)
  in uint64_t b200_radio_ctrl_core_impl::wait_for_ack(bool)
  at /usr/local/src/uhd/host/lib/usrp/b200/b200_radio_ctrl_core.cpp:264

> > > Done (return code 1)

Generating: '/home/labpc/secbeedir/SecBee/top_block.py'

Executing: /usr/bin/python2 -u /home/labpc/secbeedir/SecBee/top_block.py

linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.011.000.git-47-g3e352429

(top_block.py:24407): IBUS-WARNING **: The owner of /home/labpc/.config/ibus/bus is not root!
-- Detected Device: B200
-- Operating over USB 3.
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Setting master clock rate selection to 'automatic'.
-- Asking for clock rate 16.000000 MHz... 
-- Actually got clock rate 16.000000 MHz.
-- Performing timer loopback test... pass
-- Asking for clock rate 32.000000 MHz... 
-- Actually got clock rate 32.000000 MHz.
-- Performing timer loopback test... pass

If you need me to screenshot anything else let me know. Also, While installing this I have written down some troubleshooting solutions so I can organize them and send them to you if you'd like.

**Comment by iotfu** [comment]
Ok so I fiddled around with it, at first I reinstalled everything on a fresh install of Ubuntu (not vm) and then tried a couple of things like Installing Scapy-Com and not just Scapy-Radio.
After doing this I got another error saying "ERROR: name X3BytesField is not defined."
I figured it had something to do with the I was using python 2.7 and so I downloaded Python 3.5 and something happened..

![screenshot from 2016-09-19 14 37 45](https://cloud.githubusercontent.com/assets/22129077/18630652/ae1d4ec2-7e76-11e6-8e29-1b40036540a8.png)

Does this move me forward or did f--- it up?
