### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by vsboost** [Cognosec/SecBee#6]
Hi there,

Think i followed the instructions as best as can, but program fails to load.

  File "SecBee.py", line 10, in <module>
    import scapy.layers.zigbee
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/zigbee.py", line 710, in <module>
    class ZigbeeAppDataPayloadStub(Packet):
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/zigbee.py", line 727, in ZigbeeAppDataPayloadStub
    ZigbeePayloadField("data", "", length_from=lambda pkt, s:len(s)),
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/zigbee.py", line 230, in __init__
    self.length_from = length_from
AttributeError: 'ZigbeePayloadField' object has no attribute 'length_from'

**Comment by vsboost** [comment]
Also in the instructions:

cd Zigbee Crypto
sudo **cp zigbee_crypto.so /usr/local/lib/zigbee_crypto.so** sudo cp zigbee_transkey.so /usr/local/lib/zigbee_transkey.so

I believe the file is zigbee_crypt.so and not zigbee_crypto.so

**Comment by JamesonBeebe** [comment]
This is correct vsboost. Following these instructions almost works. I am getting an error importing zigbee_transkey.so  
I have followed all of the setup instructions perfectly, and I have added /usr/local/lib to the $PYTHONPATH, however when I try to run SecBee I get the following error: 

`user@mednb099:~/Toolz/SecBee/Source$ python SecBee.py 
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "SecBee.py", line 16, in <module>
    import zigbee_transkey
ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory
user@mednb099:~/Toolz/SecBee/Source$ 
`

It appears that either python is having trouble importing zigbee_transkey, or there is an issue with libgcrypt. Any ideas?

I'm running Ubuntu 16.04LTS, everything is up to date.

Thanks

**Comment by JamesonBeebe** [comment]
This is correct vsboost. Following these instructions almost works. I am getting an error importing zigbee_transkey.so

I have followed all of the setup instructions perfectly, and I have added /usr/local/lib to the $PYTHONPATH, however when I try to run SecBee I get the following error:

user@mednb099:/Toolz/SecBee/Source$ python SecBee.py
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
File "SecBee.py", line 16, in 
import zigbee_transkey
ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory
user@mednb099:/Toolz/SecBee/Source$

It appears that either python is having trouble importing zigbee_transkey, or there is an issue with libgcrypt. Any ideas?

I'm running Ubuntu 16.04LTS, everything is up to date.

Thanks

**Comment by Sean-Huntley** [comment]
I'm having the same problem importing zigbee_transkey, has anyone got a solution?
